name: test for cross-chain-atomic-swap-cordapp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
        java-package: jdk
        architecture: x86

    - name: cache dependencies
      uses: actions/cache@v1
      env:
        cache-name: gradle-caches
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-${{ hashFiles('cross-chain-atomic-swap-cordapp/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-
          ${{ runner.os }}-cross-chain-atomic-swap-cordapp-test-
          ${{ runner.os }}-

    - name: gradlew test
      run: cd cross-chain-atomic-swap-cordapp && ./gradlew test

    - uses: actions/upload-artifact@v1
      with:
        name: upload a test report
        path: cross-chain-atomic-swap-cordapp/build/reports/tests/test
