name: Publish GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.69.2'
          extended: true

      - name: Cache dependencies
        uses: actions/cache@v1
        env:
          cache-name: npm-caches
        with:
          path: ./docs/node_modules
          key: gh-pages-${{ env.cache-name }}-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            gh-pages-${{ env.cache-name }}-${{ hashFiles('docs/yarn.lock') }}
            gh-pages-${{ env.cache-name }}-

      - name: Install dependencies
        run: cd ./docs && yarn && git submodule update --recursive --init

      - name: Build
        run: cd ./docs && hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
