name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  JAVA_VERSION: 8

jobs:
  cross-chain-atomic-swap-cordapp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
        java-package: jdk

    - name: cache gradle wrapper
      uses: actions/cache@v1
      env:
        cache-name: gradle-wrapper
      with:
        path: ~/.gradle/wrapper
        key: cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-${{ hashFiles('cross-chain-atomic-swap-cordapp/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-${{ hashFiles('cross-chain-atomic-swap-cordapp/gradle/wrapper/gradle-wrapper.properties') }}
          cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-

    - name: cache dependencies
      uses: actions/cache@v1
      env:
        cache-name: gradle-caches
      with:
        path: ~/.gradle/caches
        key: cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-${{ hashFiles('cross-chain-atomic-swap-cordapp/build.gradle') }}
        restore-keys: |
          cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-${{ hashFiles('cross-chain-atomic-swap-cordapp/build.gradle') }}
          cross-chain-atomic-swap-cordapp-test-${{ env.cache-name }}-

    - name: gradlew test
      run: cd cross-chain-atomic-swap-cordapp && ./gradlew test
